{{- if .Values.rbac.create -}}
{{- $rbac := .Files.Get "files/rbac.yaml" | fromYaml  }}
{{- $rbacOpenShift := .Files.Get "files/rbac-openshift.yaml" | fromYaml  }}

{{- /* ClusterRole referenced by either ClusterRoleBinding or Rolebindings for all watchNamespaces*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-operator.fullname" $ }}
  labels:
    {{- include "grafana-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
  {{- toYaml $rbac.rules | nindent 2 }}
  {{- if $.Values.isOpenShift }}
  {{- toYaml $rbacOpenShift.rules | nindent 2 -}}
  {{- end }}

{{- /* Namespace scope, one or more namespaces */}}
{{- if .Values.namespaceScope }}
{{- $watchNamespaces := append (splitList "," .Values.watchNamespaces) (include "grafana-operator.namespace" .) }}
{{- range $watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grafana-operator.fullname" $ }}
  namespace: {{ trim . }}
  labels:
    {{- include "grafana-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-operator.serviceAccountName" $ }}
    namespace: {{ include "grafana-operator.namespace" $ }}
roleRef:
  kind: ClusterRole
  name: {{ include "grafana-operator.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}{{- /* range $watchNamespaces */}}

{{- else }}{{- /* namespaceScope */}}
{{- /* ClusterScope (default) */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-operator.fullname" $ }}
  labels:
    {{- include "grafana-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
roleRef:
  kind: ClusterRole
  name: {{ include "grafana-operator.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-operator.serviceAccountName" $ }}
    namespace: {{ include "grafana-operator.namespace" $ }}
{{- end }}{{- /* else namespaceScope */}}
{{- end }}{{- /* rbac.create */}}
