resources:
  - crds.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - rolebinding.yaml
  - role.yaml
patches:
  - target:
      kind: ClusterRole
    patch: |
      - op: replace
        path: /metadata/name
        value: grafana-operator-permissions
images:
  - name: ghcr.io/grafana/grafana-operator
    newTag: v5.21.3
