apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-operator-leases
subjects:
  - kind: ServiceAccount
    name: grafana-operator-controller-manager
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-operator-leases
