apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
spec:
  prometheusUrl: "http://prometheus-application-monitoring:9090"
  dashboardNamespaceSelector:
    matchLabels:
      monitoring-key: middleware
