apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: older-versions
spec:
  version: 12.1.3 # Relevant for 12.1.X or lower as jwk_set_bearer_token_file and tls_client_ca don't exist
  client:
    useKubeAuth: true
  config:
    auth.jwt:
      enabled: "true"
      header_name: Authorization
      username_claim: sub
      email_claim: sub
      auto_sign_up: "true"
      jwk_set_file: /var/run/kube-root-jwks.json
      role_attribute_path: "contains(\"kubernetes.io\".namespace, 'grafana') && 'GrafanaAdmin' || 'None'" # Assigns normal Admin unless allow_assign_grafana_admin is enabled
      role_attribute_strict: "true" # Disables auto_assign_org_role
      # allow_assign_grafana_admin: "true"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              volumeMounts:
                - mountPath: /var/run/
                  name: cluster-jwks
                  readOnly: true
          volumes:
            - name: cluster-jwks
              configMap:
                name: kube-root-jwks
                defaultMode: 0444
                items:
                  - key: jwks.json
                    path: kube-root-jwks.json
