apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: grafanafolder-sample
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana-a"
  title: "Example Folder"
