## Append samples you want in your CSV to this file as resources ##
resources:
- grafana_v1beta1_grafana.yaml
- grafana_v1beta1_grafanadashboard.yaml
- grafana_v1beta1_grafanadatasource.yaml
- grafana_v1beta1_grafanafolder.yaml
- grafana_v1beta1_grafanaalertrulegroup.yaml
- grafana_v1beta1_grafanacontactpoint.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
