## Append samples you want in your CSV to this file as resources ##
resources:
- grafana_v1beta1_grafana.yaml
- grafana_v1beta1_grafanadashboard.yaml
- grafana_v1beta1_grafanadatasource.yaml
- grafana_v1beta1_grafanafolder.yaml
- grafana_v1beta1_grafanaalertrulegroup.yaml
- grafana_v1beta1_grafanacontactpoint.yaml
- grafana_v1beta1_grafananotificationpolicy.yaml
- grafana_v1beta1_grafananotificationtemplate.yaml
- grafana_v1beta1_grafananotificationpolicyroute.yaml
- grafana_v1beta1_grafanalibrarypanel.yaml
- grafana_v1beta1_grafanamutetiming.yaml
- grafana_v1beta1_grafanaserviceaccount.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
