apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: main-grafana
  namespace: main-grafana
spec:
  deployment:
    labels:
      app: main-grafana
  client:
    preferService: true
  ingress:
    enabled: True
    pathType: Prefix
    path: "/"
    hostName: grafana.main.unbox.xenit.io
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  service:
    name: main-grafana
    labels:
      app: main-grafana
  dashboardNamespaceSelector:
    matchLabels:
      app: main-grafana
  resources:
    # Optionally specify container resources
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
