{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-operator.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
  labels:
{{ include "grafana-operator.labels" . | nindent 4 }}
{{- end -}}
